server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location /api/ {
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        client_max_body_size 25m;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
